import sqlite3
import json

new_syl = [
    "Welcome: |8 min||00:00 - 00:05 | Welcome & V60 Pouring: Welcome the guests to the lab. Hand them a pre-brewed V60 coffee to sip immediately as they get settled.<br><br>00:05 - 00:08 | Laboratory Tour: Walk the guests through the lab space, showing the roasting setup, espresso bars, and coffee testing equipment.",

    'Part 1: V60|43 min||00:08 - 00:14 | Intro to Filtered Coffee: Question to guests: "Cual es un filtrado? What is a filtered coffee?" Explanation: It is a beverage made with coffee grounds where water flows through a porous material. A filtered coffee is a clean, lighter form of making coffee, offering a sharp contrast to a heavy espresso.<br><br>00:14 - 00:16 | Intro to Equipment: Introduce the tools: Kettle, Grinder, scale, filters, and drippers. Point out the variety: "Here you can see different kinds of drippers: Origami, V60, V70, Tornado, etc."<br><br>00:16 - 00:24 | Instructor Demonstration: Walk through the brewing process with everything pre-staged (grounds ready, water hot). Hand out the recipe cards to the guests so they can follow along visually.<br><br>00:24 - 00:26 | Talk About the Coffee: Briefly explain the origin, roast profile, and flavor notes of the specific coffee bean they are about to brew.<br><br>00:26 - 00:46 | Hands-On Exercise: Cue: "Everybody to your station: Follow my instructions please and use your recipe card."<br>Step 1: Warm up your water to 86°C (push the button on the kettle).<br>Step 2: Put your beans into the grinder (the grind size is already preset for you).<br>Step 3: Purge (rinse) your paper filter with hot water.<br>Step 4: Put your server on the scale and the dripper on top. Click the \'Tare\' button to set the scale to zero. Put the grounds into the dripper.<br>Step 5: Weigh the coffee and make sure there are exactly 15 grams. Tare the scale to zero again.<br>Step 6: When the water hits 86°C, pour the bloom: 45 grams of water. Wait 1 minute.<br>Step 7: Before all the water leaves the dripper, pour your second round of water: bring the total up by 100g (scale reads 145g).<br>Step 8: Before that water completely leaves the dripper, make your final pour of 90g (final scale reading: 235g).<br><br>00:46 - 00:51 | Conclusion & Evaluation: Cue: "Try it!" Everyone tastes each other\'s brews. Discuss how to improve or why a specific cup came out tasting the way it did.',

    "Part 2: Espresso Machine|45 min||00:51 - 00:57 | Intro & Tools: Question to guests: \"What can we make with an espresso machine?\" Explanation: Beyond an espresso, we use it to create milk-based drinks like a cappuccino and a flat white. Introduce the tools: Espresso Machine, portafilter, Grinder, Scale, Filter Basket, WDT Tool, tamper, and milk Jug.<br><br>00:57 - 01:27 | Hands-On Espresso Steps & Milk Texturing: The Steps to Make an Espresso:<br>Put the portafilter on the scale and set the scale to 0.<br>Press the portafilter against the grinder trigger and dose exactly 18 grams.<br>Use the WDT tool to stir and evenly distribute the grounds.<br>Use the tamper to press straight down firmly and evenly.<br>Place your scale onto the machine base. Lock the portafilter into the group head, place your cup on the scale, and set it to 0.<br>Press the extraction button and start the timer on the scale simultaneously.<br>Next (The Finish): Stop the shot when it hits your recipe target weight (e.g., 36 grams of liquid espresso in roughly 25–30 seconds).<br><br>The Milk Step: Purge the steam wand, texture cold milk in your jug to a glossy microfoam texture, and pour it into the espresso using the correct ratios for a cappuccino or flat white.<br><br>01:27 - 01:36 | Drinks Practice & Tasting: Allow guests to pull their own shots, steam their milk, build their custom drinks at their stations, and drink them.",

    "Part 3: Roasting|54 min||We run a batch roast together and cover the fundamentals of the roasting process. At the end, everyone takes home 160 grams of freshly roasted coffee."
]

conn = sqlite3.connect('coffee.db')
cursor = conn.cursor()
cursor.execute("UPDATE Experiences SET Syllabus = ? WHERE Id = 14", (json.dumps(new_syl),))
conn.commit()
conn.close()
print("Updated database.")
