// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TheBestBean.Data;

#nullable disable

namespace TheBestBean.Migrations
{
    [DbContext(typeof(TheBestBeanContext))]
    [Migration("20251125225431_CheckCuppingEndpoint")]
    partial class CheckCuppingEndpoint
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("TheBestBean.Models.BeanInventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("CostPerKg")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ElevationMeters")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Farmer")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int?>("HarvestYear")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("LotNumber")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Process")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PurchaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalKg")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Variety")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BeanInventories");
                });

            modelBuilder.Entity("TheBestBean.Models.CoffeeBean", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CoffeeFarmId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CoffeeRegionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FlavorProfile")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<int>("OriginCountryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProcessingMethod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(3, 1)");

                    b.HasKey("Id");

                    b.HasIndex("CoffeeFarmId");

                    b.HasIndex("CoffeeRegionId");

                    b.HasIndex("OriginCountryId");

                    b.ToTable("CoffeeBean");
                });

            modelBuilder.Entity("TheBestBean.Models.CoffeeFarm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CoffeeFarm");
                });

            modelBuilder.Entity("TheBestBean.Models.CoffeeRegion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CoffeeRegion");
                });

            modelBuilder.Entity("TheBestBean.Models.CuppingScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("AcidityIntensity")
                        .HasColumnType("decimal(4, 2)");

                    b.Property<decimal?>("AcidityScore")
                        .HasColumnType("decimal(4, 2)");

                    b.Property<decimal?>("AftertasteScore")
                        .HasColumnType("decimal(4, 2)");

                    b.Property<decimal?>("BalanceScore")
                        .HasColumnType("decimal(4, 2)");

                    b.Property<decimal?>("BodyIntensity")
                        .HasColumnType("decimal(4, 2)");

                    b.Property<decimal?>("BodyScore")
                        .HasColumnType("decimal(4, 2)");

                    b.Property<int?>("CleanCupChecks")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("CupperName")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CuppingDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DefectCups")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("FinalScore")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal?>("FlavorScore")
                        .HasColumnType("decimal(4, 2)");

                    b.Property<decimal?>("FragranceBreak")
                        .HasColumnType("decimal(4, 2)");

                    b.Property<decimal?>("FragranceDry")
                        .HasColumnType("decimal(4, 2)");

                    b.Property<decimal?>("FragranceScore")
                        .HasColumnType("decimal(4, 2)");

                    b.Property<string>("LotNumber")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("OverallScore")
                        .HasColumnType("decimal(4, 2)");

                    b.Property<int>("RoastBatchId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RoastLevel")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SweetnessChecks")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UniformityChecks")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RoastBatchId");

                    b.ToTable("CuppingScores");
                });

            modelBuilder.Entity("TheBestBean.Models.FarmProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClimateNotes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CoffeeVarieties")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CommunityImpact")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("EnvironmentalFeatures")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FarmName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FarmPhotos")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FarmStory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FarmerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FarmingPhilosophy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GPSLatitude")
                        .HasColumnType("TEXT");

                    b.Property<string>("GPSLongitude")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProcessingMethod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("QualityHighlights")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("QualityRating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("RelatedSurveyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SustainabilityPractices")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RelatedSurveyId");

                    b.ToTable("FarmProfiles");
                });

            modelBuilder.Entity("TheBestBean.Models.FarmerSurvey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("AnnualProductionKg")
                        .HasColumnType("TEXT");

                    b.Property<string>("Aspect")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Certifications")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ChallengesMentioned")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("CoffeePlantedAreaHa")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CoffeePlantingYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CooperativeMembership")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("DrainageConditions")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("DryingMethod")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("DryingTime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ElevationMeters")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErosionRisks")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FarmName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("FarmerName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("FermentationType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FertilizationType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("FollowUpRequired")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GpsCoordinates")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("HarvestingMethod")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasIntercropping")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IntercroppingDetails")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("LaborSystem")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("OtherCrops")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PestDiseasePresence")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotographsTaken")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PlantingDensityTreesHa")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProcessingMethod")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PruningMethod")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("QualityRating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RainfallPatterns")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShadeTrees")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SlopeType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("SoilDepth")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SoilFertilityManagement")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SoilType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("StorageConditions")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SurveyDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SurveyNotes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SurveyPhotoPath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("TemperatureRange")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TotalFarmSizeHa")
                        .HasColumnType("TEXT");

                    b.Property<string>("TraceabilitySystem")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("UniqueQualities")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("VarietiesGrown")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("WaterSource")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FarmerSurveys");
                });

            modelBuilder.Entity("TheBestBean.Models.OriginCountry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("OriginCountry");
                });

            modelBuilder.Entity("TheBestBean.Models.RoastBatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BeanInventoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("DTRPercent")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<int?>("DropTime")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DryEndTime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EventsJson")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FirstCrackTime")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("GreenWeightGrams")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RoastDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoastLevel")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("RoastTimeSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("RoastedWeightGrams")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("TemperatureDataJson")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TurnPointTime")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("WeightLossPercent")
                        .HasColumnType("decimal(5, 2)");

                    b.HasKey("Id");

                    b.HasIndex("BeanInventoryId");

                    b.ToTable("RoastBatches");
                });

            modelBuilder.Entity("TheBestBean.Models.CoffeeBean", b =>
                {
                    b.HasOne("TheBestBean.Models.CoffeeFarm", "CoffeeFarm")
                        .WithMany()
                        .HasForeignKey("CoffeeFarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheBestBean.Models.CoffeeRegion", "CoffeeRegion")
                        .WithMany()
                        .HasForeignKey("CoffeeRegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheBestBean.Models.OriginCountry", "OriginCountry")
                        .WithMany()
                        .HasForeignKey("OriginCountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CoffeeFarm");

                    b.Navigation("CoffeeRegion");

                    b.Navigation("OriginCountry");
                });

            modelBuilder.Entity("TheBestBean.Models.CuppingScore", b =>
                {
                    b.HasOne("TheBestBean.Models.RoastBatch", "RoastBatch")
                        .WithMany("CuppingScores")
                        .HasForeignKey("RoastBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoastBatch");
                });

            modelBuilder.Entity("TheBestBean.Models.FarmProfile", b =>
                {
                    b.HasOne("TheBestBean.Models.FarmerSurvey", "RelatedSurvey")
                        .WithMany()
                        .HasForeignKey("RelatedSurveyId");

                    b.Navigation("RelatedSurvey");
                });

            modelBuilder.Entity("TheBestBean.Models.RoastBatch", b =>
                {
                    b.HasOne("TheBestBean.Models.BeanInventory", "BeanInventory")
                        .WithMany("RoastBatches")
                        .HasForeignKey("BeanInventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BeanInventory");
                });

            modelBuilder.Entity("TheBestBean.Models.BeanInventory", b =>
                {
                    b.Navigation("RoastBatches");
                });

            modelBuilder.Entity("TheBestBean.Models.RoastBatch", b =>
                {
                    b.Navigation("CuppingScores");
                });
#pragma warning restore 612, 618
        }
    }
}
